# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180301_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='Tour',
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Tourist',
        ),
    ]
