# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180302_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='timestamp',
        ),
    ]
