# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180304_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
